name: Auto JSR

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'src/**'
      - 'styles/**'

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.bump.outputs.new_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Next Version
        id: bump
        uses: mathieudutour/github-tag-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    runs-on: ubuntu-latest
    needs: determine-version
    permissions:
      contents: write
    outputs:
      version: ${{ steps.create-release.outputs.version }}
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Release
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=v${{ needs.determine-version.outputs.next_version }}
          gh release create $VERSION \
            --title "Release $VERSION" \
            --generate-notes \
            --repo ${{ github.repository }}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "upload_url=${{ github.server_url }}/${{ github.repository }}/releases/$VERSION/assets/upload" >> $GITHUB_OUTPUT

  build-and-upload:
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: Upload Artifact (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          gh release upload ${{ needs.create-release.outputs.version }} \
            ./dist/JSR-Setup-${{ needs.create-release.outputs.version }}.exe \
            --repo ${{ github.repository }}

      - name: Upload Artifact (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          gh release upload ${{ needs.create-release.outputs.version }} \
            ./dist/JSR-${{ needs.create-release.outputs.version }}.dmg \
            --repo ${{ github.repository }}

      - name: Upload Artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          gh release upload ${{ needs.create-release.outputs.version }} \
            ./dist/JSR-${{ needs.create-release.outputs.version }}.AppImage \
            --repo ${{ github.repository }}
