name: Build and Release (Fixed Permissions)

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    # Обновленные разрешения для GitHub Actions
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
      discussions: write
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
      - name: Проверка кода
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Настройка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          
      - name: Установка зависимостей
        run: npm ci
        
      # Настройка GitHub CLI для создания релизов
      - name: Настройка GitHub CLI
        uses: cli/cli-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Сборка и публикация для Windows
        if: matrix.os == 'windows-latest'
        env:
          # Используем токен с расширенными правами
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Проверяем права токена
          gh auth status
          # Используем альтернативный метод создания релиза
          npm run release:cli:win
        
      - name: Сборка и публикация для macOS
        if: matrix.os == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release:cli:mac
        
      - name: Сборка и публикация для Linux
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release:cli:linux