# Workflow for building Tauri app on pull requests
name: Tauri Build PR

# Trigger on pull requests to main branch that modify Tauri app files or this workflow
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'JSR-Tauri/jsr-tauri-app/**'
      - '.github/workflows/tauri-build-pr.yml'

# Required permissions for the workflow
permissions:
  contents: write    # Needed for checkout and artifact handling
  pull-requests: write  # Needed for commenting on PRs
  issues: write      # Needed for issue management

jobs:
  build-tauri:
    name: Build Tauri App (${{ matrix.platform }})
    strategy:
      # Continue with other platforms if one fails
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './JSR-Tauri/jsr-tauri-app/src/package-lock.json'
        continue-on-error: true

      # Setup Rust environment
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # Install Linux-specific dependencies
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./JSR-Tauri/jsr-tauri-app/src

      # Build the Tauri application
      - name: Build Tauri application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.jsr_token }}
        with:
          projectPath: './JSR-Tauri/jsr-tauri-app/src'

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-artifacts-${{ matrix.platform }}
          path: |
            ./JSR-Tauri/jsr-tauri-app/src/src-tauri/target/release/bundle/msi/*.msi
            ./JSR-Tauri/jsr-tauri-app/src/src-tauri/target/release/bundle/nsis/*.exe
            ./JSR-Tauri/jsr-tauri-app/src/src-tauri/target/release/bundle/dmg/*.dmg
            ./JSR-Tauri/jsr-tauri-app/src/src-tauri/target/release/bundle/deb/*.deb
            ./JSR-Tauri/jsr-tauri-app/src/src-tauri/target/release/bundle/appimage/*.AppImage
          if-no-files-found: ignore